services:
  db:
    image: postgres:15-alpine
    container_name: tenfingers-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tenfingers}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tenfingers123}
      POSTGRES_DB: ${POSTGRES_DB:-tenfingers}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tenfingers-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-tenfingers}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tenfingers-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-4000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://tenfingers:tenfingers123@db:5432/tenfingers}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key-change-in-production}
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tenfingers-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tenfingers-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:4000}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - tenfingers-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  tenfingers-network:
    driver: bridge
